### PR TITLE
Fixed missing internationalization and updated Chinese Simplified translations

### PR DESCRIPTION
**Pull request by geeksteph**
## Proposed Changes
1. 

## Additional Info.
Any additional info goes here

### CODE REVIEW

**Comment by geeksteph** [comment]
Ready for review.

**Comment by gpoliko** [comment]
@geeksteph could you please fetch the latest changes. I believe the missing locales was picked up in https://github.com/CovidEngine/vaxxnz/pull/260. Thank you 🙏🏾

**Comment by gpoliko** [comment]
@geeksteph I'm going to close this PR in favour of your work in https://github.com/CovidEngine/vaxxnz/pull/262 and the work in https://github.com/CovidEngine/vaxxnz/pull/260.

**Comment by geeksteph** [comment]
@gpoliko Chinese Simplified and Chinese Traditional are 2 different languages.

**Comment by geeksteph** [comment]
I'll create a new PR for just Chinese Simplified then.

**Comment by gpoliko** [comment]
@geeksteph big oopsie on my part 😅

**Review by gpoliko — APPROVED** [review]
Happy days! Sorry for the mixup @geeksteph

**Comment by geeksteph** [comment]
That's all good, thanks @gpoliko :)

**Pull request merged**
