### PR TITLE
Fixed the Loading state layout alignment

### PR DESCRIPTION
**Pull request by Abhijnan-Bajpai**
Fixed this [issue](https://github.com/CovidEngine/vaxxnz/issues/74) at two places.

### CODE REVIEW

**Comment by noway** [comment]
@Abhijnan-Bajpai thanks so much. Can you bring your branch up to date so there are no merge conflicts? Will merge straight after. Cheers.

**Comment by Abhijnan-Bajpai** [comment]
Is it fine now @noway ?

**Comment by noway** [comment]
The diff shows way too many additions 😅 i'll jump in and try to figure it out

**Comment by noway** [comment]
@Abhijnan-Bajpai 
do you wanna delete the backup files you've created
```
.vscode/settings.json
src/booking/BookingCalendar_BACKUP_72154.tsx
src/booking/BookingCalendar_BASE_72154.tsx
src/booking/BookingCalendar_LOCAL_72154.tsx
src/booking/BookingCalendar_REMOTE_72154.tsx
```

then it's good to go

**Review by noway — APPROVED** [review]
just delete the backup files and we good to go

**Comment by noway** [comment]
Thank you!

**Comment by Abhijnan-Bajpai** [comment]
> Thank you!

My pleasure!

**Pull request merged**
