### PR TITLE
Added a cookie banner

### PR DESCRIPTION
**Pull request by Abhijnan-Bajpai**
Added the basic structure of a cookie bar onto the website, with reference to this [issue](https://github.com/CovidEngine/vaxxnz/issues/119)

### CODE REVIEW

**Comment by noway** [comment]
We're using Yarn and not NPM. Please delete package-lock.json 🙏🏻

**Comment by Abhijnan-Bajpai** [comment]
> We're using Yarn and not NPM. Please delete package-lock.json 🙏🏻

Sorry about that!

**Comment by noway** [comment]
@Abhijnan-Bajpai I've fixed huge diff on yarn.lock, brought your branch up to date and ran prettier.

To merge it, can we fix a few things:
- remove alert
- when your decline, do a gtag opt-out. I assume they should have a javascript call for that.
- only show cookie banner if coords are in this Bounding Box `-12.0792755076,35.9674116355,40.6576894187,58.9861052075` (Europe)

**Comment by Abhijnan-Bajpai** [comment]
> @Abhijnan-Bajpai I've fixed a big diff on yarn.lock, brought your branch up to date and ran prettier.
> 
> To merge it, can we fix a few things:
> 
> * remove alert
> * when your decline, do a gtag opt-out. I assume they should have a javascript call for that.
> * only show cookie banner if coords are in this Bounding Box `-12.0792755076,35.9674116355,40.6576894187,58.9861052075` (Europe)

What kind of implementation is expected for the bounding box implementation? Should I go ahead and use the navigator.geolocation?

**Comment by Abhijnan-Bajpai** [comment]
> @Abhijnan-Bajpai I've fixed a big diff on yarn.lock, brought your branch up to date and ran prettier.
> 
> To merge it, can we fix a few things:
> 
> * remove alert
> * when your decline, do a gtag opt-out. I assume they should have a javascript call for that.
> * only show cookie banner if coords are in this Bounding Box `-12.0792755076,35.9674116355,40.6576894187,58.9861052075` (Europe)

Also, will I be needing the MEASUREMENT_ID for using the gtag opt-out as mentioned in the docs [here](https://developers.google.com/analytics/devguides/collection/ga4/disable-analytics)?

**Comment by noway** [comment]
@Abhijnan-Bajpai 
>Also, will I be needing the MEASUREMENT_ID for using the gtag opt-out as mentioned in the docs here?

Yep, probably. Here's our.
image
G-PXHVR76F27

>What kind of implementation is expected for the bounding box? Should I go ahead and use the navigator.geolocation?

You can get coords from here:
https://github.com/CovidEngine/vaxxnz/blob/main/src/App.tsx#L15

Also it's pretty handy to check for Bbox like so:
https://github.com/CovidEngine/vaxxnz/blob/main/src/calendar/booking/BookingData.ts#L48

**Comment by Abhijnan-Bajpai** [comment]
@noway could you have a look at my implementation of the suggested changes

**Comment by noway** [comment]
This is looking great! I will review this with a fresh eye tomorrow, but so far looking good 👍🏻

**Comment by noway** [comment]
@waltzaround can maybe give it some UI love in a separate PR

**Review by noway — APPROVED** [review]
great work 👍🏻

**Comment by Abhijnan-Bajpai** [comment]
> great work 👍🏻

Thanks for helping me out!

**Pull request merged**
