### PR TITLE
Add tests to existing utils functions

### PR DESCRIPTION
**Pull request by rquitales**
This PR adds more tests to existing functions within `src/utils`, as well as improving code documentation and adding return types.

### CODE REVIEW

**Comment by noway** [comment]
Looks awesome!

Netlify fails with this... Do you know why? `main` is building fine
```
9:40:35 PM: Failed to compile.
9:40:35 PM: 
9:40:35 PM: /opt/build/repo/src/calendar/modal/CalendarModalContent.tsx
9:40:35 PM: TypeScript error in /opt/build/repo/src/calendar/modal/CalendarModalContent.tsx(30,37):
9:40:35 PM: Argument of type '(location: CalendarLocation) => number' is not assignable to parameter of type '(note: CalendarLocation) => CalendarLocation'.
9:40:35 PM:   Type 'number' is not assignable to type 'CalendarLocation'.  TS2345
9:40:35 PM:     28 |   coords: Coords
9:40:35 PM:     29 | ): CalendarLocation[] {
9:40:35 PM:   > 30 |   return sortByAsc(locations ?? [], (location) => {
9:40:35 PM:        |                                     ^
9:40:35 PM:     31 |     const distanceKm = getDistanceKm(
9:40:35 PM:     32 |       coords,
9:40:35 PM:     33 |       "isBooking" in location
```

**Comment by rquitales** [comment]
> Looks awesome!
> 
> Netlify fails with this... Do you know why? `main` is building fine
> 
> ```
> 9:40:35 PM: Failed to compile.
> 9:40:35 PM: 
> 9:40:35 PM: /opt/build/repo/src/calendar/modal/CalendarModalContent.tsx
> 9:40:35 PM: TypeScript error in /opt/build/repo/src/calendar/modal/CalendarModalContent.tsx(30,37):
> 9:40:35 PM: Argument of type '(location: CalendarLocation) => number' is not assignable to parameter of type '(note: CalendarLocation) => CalendarLocation'.
> 9:40:35 PM:   Type 'number' is not assignable to type 'CalendarLocation'.  TS2345
> 9:40:35 PM:     28 |   coords: Coords
> 9:40:35 PM:     29 | ): CalendarLocation[] {
> 9:40:35 PM:   > 30 |   return sortByAsc(locations ?? [], (location) => {
> 9:40:35 PM:        |                                     ^
> 9:40:35 PM:     31 |     const distanceKm = getDistanceKm(
> 9:40:35 PM:     32 |       coords,
> 9:40:35 PM:     33 |       "isBooking" in location
> ```

Yeah, I messed up the return type for the comparator function. New commit pushed to fix this.

**Comment by noway** [comment]
Looking at it now

**Review by noway — APPROVED** [review]
LGTM, test coverage go brr 🚀

**Pull request merged**
