### PR TITLE
Removed duplicate keys in the Arabic json.

### PR DESCRIPTION
**Pull request by al-abbas-nz**
1. Removed duplicate keys in the Arabic json.

### CODE REVIEW

**Comment by noway** [comment]
I'll have a look tonight 👍🏻

**Comment by noway** [comment]
There was a big diff on yarn.lock, I fixed it. You might have did an `npm install` instead of `yarn install` and committed it by accident 👍🏻

**Review by noway — APPROVED** [review]
LGTM, nice work 👍🏻

**Comment by al-abbas-nz** [comment]
> There was a big diff on yarn.lock, I fixed it. You might have did an `npm install` instead of `yarn install` and committed it by accident 👍🏻

Thanks for clearing that up! Much appreciated.

**Pull request merged**
