### PR TITLE
Fix/go back reverts to default location

### PR DESCRIPTION
**Pull request by tausani-ah-chong**
Hey Team!

This is the fix for the bug in #39 

For some strange reason, the current `useDefaultCoords` & `useDefaultPlaceName` wasn't working as intended, so I have simplified the logic a bit. Open to your thoughts!

I have also added `DEFAULT_LOCATION` to `utils` so can be updated, depending on what we want our initial location to be when the site gets loaded.

### CODE REVIEW

**Comment by noway** [comment]
brilliant, will review tomorrow (as in today)

**Review by oeed — APPROVED** [review]
Looks good to me, this logic definitely makes more sense. Thanks @tausani-ah-chong!

Free to merge if you're happy @noway

**Review by noway — APPROVED** [review]

**Comment by noway** [comment]
Thank you @tausani-ah-chong. I've given it a test and i think it's better than what we have now. 

I actually have an idea of how we can improve even further.

**Comment by tausani-ah-chong** [comment]
> Thank you @tausani-ah-chong. I've given it a test and i think it's better than what we have now.
> 
> I actually have an idea of how we can improve even further.

Awesome keen to know what the improvement is!

**Comment by noway** [comment]
@tausani-ah-chong sorry today been hectic. here is what i think the improvement is.

What if we store lat, lng and placeName state in URL search params? And when we setCoords or setPlaceName, we push to history api directly, without extra state, and then we don't need to have all those unnecessary useEffects. Make URL search params The Single Source of Truth.

so if we need to change lat, lng or placeName ANYWHERE we do `window.history.pushState`

thoughts?

**Comment by tausani-ah-chong** [comment]
@noway Yeah thats sounds good! My only concern is just for the initial/default location, when a user goes to the site with no params in the URL. Or could this be stored as the initial state in useState?

**Comment by oeed** [comment]
I'd just do something a long the lines of 'location = param location if it is set, otherwise use the default location'.

**Comment by noway** [comment]
@tausani-ah-chong we could treat `undefined` lat/lng as Auckland CBD. That would be pretty neat. So `useSearchParams` could return `{lat: undefined, lng: undefined, placeName: undefined}`, and then we could have "processSearchParams" function and it would replace `undefined`s with Auckland CBD coordinates.

**Comment by noway** [comment]
so that way we can avoid useState and keep all "state" in URL. let me know if it makes sense! :-)

**Comment by tausani-ah-chong** [comment]
Nice! Yes this makes sense

**Pull request merged**
