### PR TITLE
Fix: format slot times according to locale

### LINKED ISSUE #187: Format slot times according to locale
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when time slots are not in my language
image

**Describe the solution you'd like**
I've tried using `toLocaleTimeString`, but had little luck? It seemed a bit buggy, maybe just me. Maybe there's a `date-fns` function for this?

**Additional context**
Gotta watch out for "00:00 pm" (which doesn't make any sense, should be "12:00 pm"). Last time I tried I stumbled into that.

### PR DESCRIPTION
**Pull request by KevinSJ**
## Proposed Changes
1. Added a function to parse and format slot time based on language

## Additional Info.
Closes #187

### CODE REVIEW

**Comment by noway** [comment]
Awesome 💯 ! Unfortunately some of the slots are showing as "00:00pm":
image

I don't think it makes sense. Can we find a way to fix that? :-)

**Comment by KevinSJ** [comment]
@noway This might be a browser specific issue. I tried several browsers and they all seems to work fine, that's why I decided to use this solution. What browser are you using?

**Comment by noway** [comment]
I'm using Chrome 93 on Mac OS

**Comment by KevinSJ** [comment]
@noway I will try to use the format function from date-fns later today and see if it fix the issue.

**Comment by noway** [comment]
Awesome, looking forward to that!

**Comment by KevinSJ** [comment]
Hey @noway, can you give it a go once you see this? I kinda hard coded the format string, still unsure if this would fix the issue, so put the previous code in comment, if it does fix, I will remove them.

**Comment by noway** [comment]
> I kinda hard coded the format string
totally fine i reckon.

@KevinSJ this seems to fix it! I'll give this a proper look with a fresh eye tomorrow (today)

**Review by noway — APPROVED** [review]
I've tested every language, seemed to be working all good to me. Nice work 👍🏻

**Comment by KevinSJ** [comment]
Actually, I have some code that I would like to remove, they are commented out. Maybe in another PR then.

**Comment by noway** [comment]
sounds good!

**Pull request merged**
