### PR TITLE
Fix/delete crowdsourced collisions

### LINKED ISSUE #239: Remove crowdsourced locations which been listed on healhthpoint
**Describe the bug**
Remove crowdsourced locations which been listed on healthpoint

**To Reproduce**

1. Go to vaxx.nz
2. Find auckland airport
3. It's listed twice

**Additional context**
Build a collision finder which removed crowdsourced locations

### PR DESCRIPTION
**Pull request by noway**
## Proposed Changes
1. Added a script which shows only unique crowdsourced locations
2. Deleted all but 1 crowdsourced locations because script told me that only 1 of them is uniuq

## Additional Info.
The one location left is `Unichem Taieri Pharmacy`
run `yarn uniqcrowdsourced` to get a list of unique crowdsourced locations

closes #239

### CODE REVIEW

**Comment by oeed** [comment]
Is Highbrook now showing up?

**Comment by noway** [comment]
@oeed Highbrook wasn't in crowdsourced?

**Comment by oeed** [comment]
Oh okay, if it's not showing in HP data we should probably add. But that can be separate. LGTM - glad so many are now on HP

**Review by waltzaround — APPROVED** [review]

**Review by wseagar — APPROVED** [review]
LGTM

**Pull request merged**
