### PR TITLE
Add Indonesian translation for vaxx

### PR DESCRIPTION
**Pull request by edwardtandjung**
Changes to lang file

### CODE REVIEW

**Review by waltzaround — APPROVED** [review]
looks good to me

**Comment by olafwrieden** [comment]
Please import the locale and add to `locale.ts` to internationalise the "Last updated x minutes ago" part.

**Comment by waltzaround** [comment]
@olafwrieden looks like its been pushed

**Comment by olafwrieden** [comment]
> @olafwrieden looks like its been pushed

I don't see it - there should be an entry in the following:

```javascript
const supportedDateLocale: { [localeString: string]: Locale } = {
  "en-NZ": enNZ,
  "de-DE": de,
  "ms-MY": mn, // Same issue
  "es-ES": es,
  "ru-RU": ru,
  "vi-VN": vi, // Don't ask me i18 locale string is different than date-fns locale string so ¯\_(ツ)_/¯
  "zh-TW": zhTW,
  "zh-CN": zhCN,
};
```

**Review by noway — APPROVED** [review]
LGTM, nice work 💯

**Comment by waltzaround** [comment]
> ```js
> supportedDateLocale:
> ```

ah one sec, will request it

**Pull request merged**
