### PR TITLE
Add number of vaccination centres to calendar modal

### PR DESCRIPTION
**Pull request by rquitales**
This PR adds a new text string for each date to also display the number of vaccination centres that have available booking slots.

This allows users to know if all available slots are for a specific vaccination centre, or not, easily. Potentially helpful if they are monitoring slots/locations for a specific day.

This address #37 

---

Screen Shot 2021-09-07 at 9 57 06 PM

### CODE REVIEW

**Comment by waltzaround** [comment]
Thoughts on swapping out the phrase vaccination centres with an icon like https://fontawesome.com/v5.15/icons/medkit?style=solid ?

**Review by olafwrieden — CHANGES_REQUESTED** [review]
@rquitales thank you for submitting this PR. We are happy to approve if you "iconify" the stats with (Font Awesome icons for example, and slightly smaller font). This way, we don't convolute the calendar with too much information. We look forward to your changes.

**Comment by rquitales** [comment]
@olafwrieden @waltzaround Have added the suggested medkit icon, and a clock icon. Have also shrunken the text size. I don't think we should completely remove the phrase `vaccination centres` as it will likely be non-intuitive for most users if we only just had icons. As a compromise, I've replaced that phrase with the much shorter `locations`.

Screenshot:
Screen Shot 2021-09-07 at 10 59 05 PM

**Comment by noway** [comment]
@rquitales can you discuss this with us on Discord https://discord.gg/aT7HQxFu

**Comment by noway** [comment]
@rquitales we've been reviewing your changeset and we think it's a bit hard to scan. 

we've read your user story..

been exploring a few options.. what do you think about showing the distance to the closest available location on the day?

Screen Shot 2021-09-07 at 11 39 48 PM
Screen Shot 2021-09-07 at 11 39 48 PM

**Comment by noway** [comment]
also, thanks a lot for bringing the PR up to date.. really appreciate it. 

we're really keen to jump in voice chat (in Discord) and discuss it though. see the invite above.

**Pull request closed without merging**
