### PR TITLE
Chinese Simplified translations updates

### PR DESCRIPTION
**Pull request by geeksteph**
WIP

### CODE REVIEW

**Comment by geeksteph** [comment]
Chinese-Simplified translations updates

**Comment by geeksteph** [comment]
Chinese-Simplified translations updates

**Comment by noway** [comment]
@geeksteph thanks for updating it! ping me when it's finished and i'll review. cheers.

**Comment by geeksteph** [comment]
Minor updates

**Comment by geeksteph** [comment]
Done with the updates, thanks！

**Review by noway — APPROVED** [review]
LGTM, nice work!

**Pull request merged**
