### PR TITLE
Fix Husky for Windows, GitBash and Yarn

### PR DESCRIPTION
**Pull request by gpoliko**
Added work around for Husky git hooks as per Husky [docs](https://typicode.github.io/husky/#/?id=yarn-on-windows)

This should address issue, https://github.com/CovidEngine/vaxxnz/issues/196

### CODE REVIEW

**Comment by noway** [comment]
@wseagar will test it, his on Windows 🔥

**Comment by gpoliko** [comment]
**UPDATE**
Issue persists. New behaviour when committing changes:

1.  Husky pre-commit hook triggers lint-staged.
2. Prettier runs and formats any lines of code that needs to be formatted.
3. Formatting is reverted and commit is rejected.

**Comment by gpoliko** [comment]
Should be all good to go for our Windows contributors 👍🏾

**Comment by noway** [comment]
Nice! @wseagar you have a Windows, can you please test 🙏🏻

**Comment by noway** [comment]
I tested this PR and it works on MacOS... @wseagar can you test on Windows please 🙏🏻

**Review by JacksonLaw — APPROVED** [review]
Looks good. I changed some formatting, committed, and it was fixed in the final file. 
On windows 10

**Comment by noway** [comment]
@al-abbas-nz reported that it worked for him 🎉

**Pull request merged**
