### PR TITLE
Removed react-markdown package && Improved legal page styling

### PR DESCRIPTION
**Pull request by shikharvashistha**
## Proposed Changes
1.  Fixes : #268 && #269

## Additional Info.
Greetings of the day @noway,

I have remove the react-markdown package. Please review the pr and let me know in case of any suggestions/changes if required.

Thanks & Regards
@shikharvashistha

### CODE REVIEW

**Comment by noway** [comment]
Hello @shikharvashistha, this is great. Can you please fix the build? Also, in order for this to work properly, we want to convert markdown content into JSX. 

So `terms`, `privacy` and `cookie` should be converted to proper React components.

**Comment by noway** [comment]
Please make sure the styling is also somewhat retained. Doesn't have to be perfect, but still want to have bolds, bullet points, headers etc. Cheers 🙏🏻 
image

**Comment by shikharvashistha** [comment]
> Please make sure the styling is also somewhat retained. Doesn't have to be perfect, but still want to have bolds, bullet points, headers etc. Cheers 🙏🏻
> image

Fixed ! 👍

**Comment by noway** [comment]
Hey @shikharvashistha, this is how your changes look currently: https://deploy-preview-276--vaxxnz.netlify.app/terms-and-conditions

In order to fix it fully, you want to:
- create a new component for a legal page (one of the `Terms`, `Privacy` and `Cookie`)
- go to the main website https://vaxx.nz/terms-and-conditions
- open devtools
- select the rendered legal content in devtools -> Edit as HTML and copy the HTML
- copy paste that HTML into the component you've just created.
- then use that component in place of <ReactMarkdown>
Rinse and repeat for the 3 legal pages.

I'm available on the vaxx.nz Discord server, you can find the invite here: https://github.com/CovidEngine/vaxxnz/blob/main/CONTRIBUTING.md

Cheers.

**Comment by shikharvashistha** [comment]
> Hey @shikharvashistha, this is how your changes look currently: https://deploy-preview-276--vaxxnz.netlify.app/terms-and-conditions
> 
> In order to fix it fully, you want to:
> 
> * create a new component for a legal page (`Terms`, `Privacy` or `Cookie`)
> * go to the main website https://vaxx.nz/terms-and-conditions
> * open devtools
> * select the rendered legal content in devtools -> Edit as HTML and copy the HTML
> * copy paste that HTML into the component you've just created.
> * then use that component in place of
> 
> Rinse and repeat for the 3 legal pages.
> 
> I'm available on the vaxx.nz Discord server to help you out, you can find the invite here: https://github.com/CovidEngine/vaxxnz/blob/main/CONTRIBUTING.md
> 
> Cheers.

Okay will fix it 👍

**Comment by noway** [comment]
@shikharvashistha awesome! let me know when the Pull Request is ready for review.

**Comment by noway** [comment]
Hi @shikharvashistha. @josephereed managed to come up with a working PR for this issue yesterday and it just got merged. This issue has been resolved. 

I'm sorry we've got to this situation, I know you've started on this PR before @josephereed, but his solution has all the styling correctly implemented, and this PR still got styling untidied.

I'm going to close this PR. Please look at other ["Good first issues"](https://github.com/CovidEngine/vaxxnz/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for an opportunity to contribute. Also, to make it easier for you, take a look at setting up local dev environment (should be as easy as `yarn install` on MacOS) as described in [CONTRIBUTING_DEV.md](https://github.com/CovidEngine/vaxxnz/blob/main/CONTRIBUTING_DEV.md)

**Comment by shikharvashistha** [comment]
> Hi @shikharvashistha. @josephereed managed to come up with a working PR for this issue yesterday and it just got merged. This issue has been resolved. 
> 
> I'm sorry we've got to this situation, I know you've started on this PR before @josephereed, but his solution has all the styling correctly implemented, and this PR still got styling untidied.
> 
> I'm going to close this PR. Please look at other ["Good first issues"](https://github.com/CovidEngine/vaxxnz/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for an opportunity to contribute. Also, to make it easier for you, take a look at setting up local dev environment (should be as easy as `yarn install` on MacOS) as described in [CONTRIBUTING_DEV.md](https://github.com/CovidEngine/vaxxnz/blob/main/CONTRIBUTING_DEV.md)

Greetings of the day @noway && @gpoliko ,

Do you think this to be a valid reason ? You guys can't even manage the workflow. Seriously I referenced the issue which was being assigned to me (as per your comment) and was clearly visible to everyone that I was the one working on it, so how come anyone cross validate your decision and start to work on it (plagiarism) ?

Thanks again for your warm welcoming hospitality. I'll take care next time before contributing here.

Best
@shikharvashistha

**Pull request closed without merging**
