### PR TITLE
Fix: Radius filter on mobile brings up keyboard

### PR DESCRIPTION
**Pull request by allen1996**
Fix issue #93

- `baseui/select` doesn't seems to provide a way to resolve this issue. Using css to hide the input as a workaround.
- Removed the maxHeight override on the Select as this seems to cause the option shift slightly to the top (see images below).

https://user-images.githubusercontent.com/6903528/132834464-8f745cdb-8c83-44fc-84eb-81833b21cbfc.mp4

https://user-images.githubusercontent.com/6903528/132834438-6ea5086f-fc4a-448f-a32a-9c0c57657b25.mp4

maxHeight-before
maxHeight-after

### CODE REVIEW

**Comment by oeed** [comment]
Yoooooooo it's @allen1996

**Comment by noway** [comment]
Yoo, long time no see!! Amazing :D

Please resolve the App.css merge conflict and we'll merge it in ☺️

**Comment by allen-bware** [comment]
what's up @oeed

**Comment by allen1996** [comment]
Yo @oeed @noway

**Comment by oeed** [comment]
Join us on Discord https://discord.gg/6qcQxf4V!

Great PR too, thanks!

**Comment by allen1996** [comment]
@oeed do you think is there a better way of doing this?

**Review by noway — APPROVED** [review]
LGTM. Pretty good way to do it.

**Pull request merged**
