### PR TITLE
Te Reo Māori Translation v1

### PR DESCRIPTION
**Pull request by gpoliko**
v1 of Te Reo Māori translation.
Missing translations at lines:

- 26: Open to the community to interpret.
- 51-52: No translation for "walk-in" or "drive-through". Open to the community to interpret.
- 86: Was missed, chasing up to update. Shouldn't be an issue right now.
- 89-91: Open to the community to interpret.

### CODE REVIEW

**Review by noway — APPROVED** [review]
LGTM, thanks so much!!

**Comment by olafwrieden** [comment]
I'm getting a colleague from Auckland to review this as well. Hoping we can ship these by tomorrow, just want to make sure we are accurate before we publish them.

**Comment by olafwrieden** [comment]
@gpoliko could you please bring this branch up to date with main and then run `yarn run sync:i18n` to sync any new translation keys.

I am in touch with an Auckland colleague and native speaker who will share his take on the translations. He's asked to either get in touch with the original translator (regarding word choice) or get them to review his translations and agree on one to move forward with. I'm hoping he will send them through tonight 🤞🏼 I'll update you as soon as I hear back. Thanks for your patience on this PR.

**Comment by gpoliko** [comment]
@olafwrieden will do that.

RE: Translations, having your colleague get in touch with the original translator will be ideal! It's probably the quickest way to reach consensus on the translation.

**Comment by olafwrieden** [comment]
@gpoliko I have received my colleague's translations. Would you be so kind to integrate them with your current translations and work with the Wellington family to come to a consensus. Of course we are open to changes in the future, but for now, we'd love to ship (and gather feedback). @noway tagging so you are across this too.

[mi.json (DW).json.zip](https://github.com/CovidEngine/vaxxnz/files/7162161/mi.json.DW.json.zip)

**Pull request merged**
