### PR TITLE
Migrate to styletron & Remove Inline styles

### LINKED ISSUE #296: Replace inline styles with styled-components
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the page flickers when loading on slow connections

**Describe the solution you'd like**
Replace inline styles with styled-components, so that styles can be injected earlier during the rendering. This will also allow us to render them in a separate .css file when we get SSR sorted.

**Additional context**
We have a few inline styles. But even just replacing the ones on the main page will help a lot. 

This is of pretty significant importance, since this will greatly improve our Cumulative Layout Shift numbers and in turn improve our SEO.

### LINKED ISSUE #302: Replace `styled-components` with `styletron-react`
**Is your feature request related to a problem? Please describe.**
Our bundle size continuous to be a big priority for us in order to reduce Core Web Vitals. 
`styled-components` takes up 34KB of our bundle (unzipped).

**Describe the solution you'd like**
Switch `styled-components` to `styletron-react` since `baseui` already forces us to use `styletron-react`.

### PR DESCRIPTION
**Pull request by Supesu**
## Proposed Changes
1. Migrate all styled-components components to styletron-react components 
2. Remove styled-components and @types/styled-components
3. Replace all inline-styles with styletron-react components
4. Fixes all eslint warnings
 
 ## Additional Information
closes #302 
closes #296

### CODE REVIEW

**Comment by Supesu** [comment]
Ready for review 👍🏻

**Comment by noway** [comment]
@Supesu sweet, i'll have a look this evening

**Review by waltzaround — CHANGES_REQUESTED** [review]
Looks good to me apart from the header and padding on walkins - once this is fixed we good to go imo

Screen Shot 2021-10-06 at 6 46 52 PM

**Comment by waltzaround** [comment]
> Looks good to me apart from the header and padding on walkins - once this is fixed we good to go imo
> 
> Screen Shot 2021-10-06 at 6 46 52 PM

Scratch this - looks like this was introduced earlier - I'll fix

**Pull request merged**
