### PR TITLE
Modal border width fix

### PR DESCRIPTION
**Pull request by dialectrical**
This PR adds a 1px, solid, light gray border to the site's modals to improve border width consistency. Addresses issue #126.

Let me know if any other tweaks need to be made on this.

### CODE REVIEW

**Comment by noway** [comment]
Sorry, I was not clear. Not the border on the modal itself, but the border on this container:
image

@dialectrical  If you can revert the modal border and implement this instead it would be great!

**Review by Francismb — APPROVED** [review]
lgtm.

**Comment by dialectrical** [comment]
Alright, committed the correct fix and removed the old stuff--let me know if it looks good.

**Review by noway — APPROVED** [review]
That looks beautiful, thank you so much!! 💯

**Comment by oeed** [comment]
Yeah in hindsight 1px does look better

**Pull request merged**
